service: serverless-express-test

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: default
  endpointType: REGIONAL
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  serverlessTest:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
